### ISSUE TITLE
Laravel-echo receives events but doesn't join channel listeners

### ISSUE THREAD

**Issue by inagamov** [mhidea/laravel-echo-nginx#1]
[My configs](https://stackoverflow.com/questions/67676458/laravel-echo-receives-events-but-doesnt-join-channel-listeners) (different nginx config).

Before I've changed my nginx config, the `https://example.com/socket.io` was returning `Cannot GET /socket.io`

After I've change the config to the one you provided, I've started receiving `{"code":0,"message":"Transport unknown"}` (as you said it should)

However, it's still not working and I can't really understand why because I can't see any errors.
Btw, I should mention that I still can see the events coming, but not users joining.

Thanks in addition for your support. Hope we will get through it!

**Comment by mhidea** [comment]
@inagamov 
Ok, you're welcome. Hopefully we can fix it.

So now proxy is working and we can go to next step. I'll add new files to make sure all configs are correct. pls check them too. Notice that my domain is **lrvl8fresh.test**.

 Check databaseConfig->redis in laravel-echo-server.json file.

check js/bootstrap.js .Make sure you have debugging mode active (line 72, localStorage.debug = '*'). Then check browser deleoper options, in console check if you see any error. If everything is ok, you must see:
```bash
engine.io-client:socket socket receive: type "pong", data "undefined" +2ms
```
_(in bootsrtap.js, **window.EchoDomain = new Echo** (line 61 ) is ment for domain name usage.)_

which means connection to server is ok. on laravel echo server , when you start server , you must see this:

 laravel-echo-server start
```bash
L A R A V E L  E C H O  S E R V E R

version 1.6.2

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

[6:04:23 PM] - Preparing authentication request to: https://lrvl8fresh.test
[6:04:23 PM] - Sending auth request to: https://lrvl8fresh.test/api/broadcasting/auth

[6:04:23 PM] - F0L3K_Z9CY9UD6d4AAAA joined channel: public
[6:04:24 PM] - F0L3K_Z9CY9UD6d4AAAA authenticated for: private-App.Models.User.1
[6:04:24 PM] - F0L3K_Z9CY9UD6d4AAAA joined channel: private-App.Models.User.1
```
which shows connection to private channel was successful.

Please check these steps to  make sure were on correct path. then we can move to next step.

**Comment by inagamov** [comment]
`->` I've enabled debugging mode and it actually says `engine.io-client:socket socket receive: type "pong", data "undefined" +101ms`

`->` I've also checked `databaseConfig.redis`, added lines I didn't have

However, I still can't see users join(
What can I check next to make everything working?

_PS: I'm starting to get discouraged, but I'm glad that there is a person like you who is trying to help, thank you. Hope we find a solution_

**Comment by mhidea** [comment]
Ok. Can you push your project to GitHub so that I can clone it and test it?
If not can you share your Laravel echo server log? You must run it in dev mode and refresh webpage where Vue component is used. It must Begin with something like this:

L A R A V E L  E C H O  S E R V E R

version 1.6.2

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

**Comment by mhidea** [comment]
And. Don't give up. Sometimes things get stuck.

**Comment by inagamov** [comment]
Ok, so a couple of days ago I've decided to make a copy of my project and remove everything that is not related to chat and broadcasting. I had done so, however, I received the same output from the `L A R A V E L E C H O S E R V E R` as on production. (no users were joining)

And my first thought was: "Hmm.. Interesting.. Might the problem be that I install `node_modules` and `composer` stuff in a wrong way"?

**How do I apply changed on production:**
1. `git clone https://github.com/user/Project`
2. `cd /var/www/html/Project/api`
3. `chmod -R 777 storage/`
4. `chmod -R 777 storage/logs`
5. `composer update`
6. `cd ../web`
7. `chmod -R 777 src/assets/img/uploads`
8. `npm install`
9. `npm run build`
10. `cd ../socket.io/`
11. `laravel-echo-server start`

So I've tried to figure it out and I decided to copy from my computer to server `node_modules` (to my frontend folder, Vue.JS folder) and `vendor` (to my backend folder, Laravel folder) folders. But, to my regret, it didn't work out.

Can you tell me how you install all the required dependencies for Laravel? I support the problem is in the `5th` command. What do you think?

**Comment by mhidea** [comment]
I would use 
```bash
composer install
```
It must create vendor folder and composer.lock file. If you run update , your project might have different versions of packages than repository
Actually you said you can get:
```json
{"code":0,"message":"Transport unknown"}
```
when you browse /socket.io/. It means echo server is listening which means it's installed.

And also I run 
```bash
laravel-echo-server start
```
in laravel root drectory. why do you cd to ../socket.io/?

Also check [System Requirements](https://github.com/tlaverdure/laravel-echo-server#system-requirementsl).

**Comment by inagamov** [comment]
My project contains 3 folders:
1. `api` (Laravel, backend)
2. `web` (Vue.JS, frontend)
3. `socket.io` (laravel-echo server)

I use `cd ../socket.io` to run laravel-echo server

**Comment by inagamov** [comment]
I've cloned my project from scratch and installed laravel dependencies using `composer install`, but it works as it previously did

**Comment by inagamov** [comment]
I'll push a clone of my project (chat-only version) to github later this day, ok?

**Comment by mhidea** [comment]
Yes. It will be easier to find the problem. Let me know when you put it on GitHub.

**Comment by inagamov** [comment]
Here is the repository: https://github.com/inagamov/chat_bug_fix

Please read the __README.md__ file, I wrote all the instructions there.

**Comment by mhidea** [comment]
in web/package.json please remove:
```json
 "socket.io": "^2.4.1",  
  "socket.io-client": "^4.1.2"
```
then add:
```json
    "socket.io-client": "^2.4",
```
Then run npm install. See if it helps. I had to do it on your repo and it worked.

**Comment by mhidea** [comment]
I just received merge email. Let me know if it was helpful.
Mine worked in local.

**Comment by inagamov** [comment]
Yeah, mine worked in local too, thanks!
I'm just trying to implement it right now on my prod. server. When I'll succeed, I'll let you know!

Thanks in addition for everything. I am very grateful that you took the time to solve my problem and showed such great patience

**Comment by inagamov** [comment]
Hmm.. for some reason it doesn't work on my prod server. I can't see users join. Any thoughts?

**Comment by inagamov** [comment]
I have some issues when I install dependencies, maybe that why?

## Laravel dependencies
So let's imagine I've just clone my project and I want to install the required dependencies.
I go to __/api__ and use `composer install`. Then I get this error:

![image](https://user-images.githubusercontent.com/69040554/122439272-2d81ce80-cfa4-11eb-8778-a151a1e5ace2.png)

What I should do? If I remove composer.lock and run this command again, I see message that says that my dependencies are __updating__, not installing.

## Vue.js dependencies
When run `npm install`, it works fine, however, gives warnings about vulnerabilities and asks to fix them running `npm audit fix` or `npm audit fix --force`, but none of them change anything. It still throws me warnings.

Then, If I remove __package-lock.json__ and __/node_modules__ and run `npm install`, it throws this:

![image](https://user-images.githubusercontent.com/69040554/122440468-3fb03c80-cfa5-11eb-88c4-766492ccf2c3.png)

I found a solution to that: `npm install --force`. But then I still get warnings and I still can't fix them.

**Comment by inagamov** [comment]
What should I do? 😔

**Comment by mhidea** [comment]
About Laravel, your php is version 8. I suggest using 7.4 ( according to the repo you gave me) if possible. 
You need to make sure nothing else depends on php 8.

**Comment by mhidea** [comment]
About vue, rename node_modules directory to something else, and delete package.lock .
Then npm install.

See if it helps.

And warnings doesn't matter for now.

**Comment by inagamov** [comment]
Well, I tried to do as much as I can by myself, but the only good result is that I've accomplished successful dependencies installation by downgrading `npm 6.14.4`, `php 7.4` and `composer 2.0.11`.

It works perfectly at the localhost, but not on the production. And the only lead is the error log from `https://example.com/socket.io`:

> GET https://example.com/socket.io/ 400 (Bad Request)

I still get `{"code":0,"message":"Transport unknown"}`, but should I really see the 400 (Bad Request) error?

**Comment by mhidea** [comment]
Ok, would you please push what you have done to the repo?

Where does it give you http 400 error? Laravel or Laravel echo or browser console?

Actually what Laravel echo server shows is super important.

**Comment by inagamov** [comment]
I get 400 error (Bad Request) as a log in browser console at `https://example.com/socket.io`

**Comment by inagamov** [comment]
I haven't done any changes, I've only applied your commitments to my real project. As I mentioned before it works on localhost, but not on the production (even with your changes)

**Comment by mhidea** [comment]
Can you give me your domain name?

**Comment by inagamov** [comment]
To get access you have to sign up first (using your real email)
> https://ehhoo.co

If `/socket.io` doesn't work, please notify me

**Comment by mhidea** [comment]
socket.io path is not accessible. 502 error. 

```html
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```

please fix nginx config. Use the sample in this repo.

**Comment by inagamov** [comment]
Before, I was just starting laravel-echo-server manually, but now it runs with the supervisor so it won't stop. Check this out
> https://ehhoo.co/socket.io

**Comment by inagamov** [comment]
I suppose that I shouldn't see `{"code":0,"message":"Transport unknown"}` because this is the output of the error (Bad Request). Instead, I should see just `Ok`

I guess we have to figure out how to fix `400 (Bad Request)` error now

**Comment by mhidea** [comment]
You are getting this error:

engine.io-client:polling polling got data 32:44/socket.io,"Invalid namespace" +457ms
browser.js:133 engine.io-client:socket socket receive: type "message", data "4/socket.io,"Invalid namespace"" +460ms
browser.js:133 socket.io-parser decoded 4/socket.io,"Invalid namespace" as {"type":4,"nsp":"/socket.io","data":"Invalid namespace"} +460ms

please check my files on this repo. 

I recommend:
use api subdomain for laravel
echo for echo server. So use something like :
```js
host: "http:\\echo.ehhoo.co"
 ```
in bootsrtap.js

then in nginx config proxy echo to port 
**Don't forget to restart everything.**


**4oo error** doesn't mater at all. that was just to see if laravel-echo-server receives anything or not.

Sorry. today is the last day I can help you with this error. I think it is related to incorrect nginx config.

**Comment by inagamov** [comment]
Ok. For some reason I can't find in your nginx config subdomain connection

**Comment by inagamov** [comment]
I can see that you use `echo.lrvl8fresh.test` in bootstrap.js, but in your nginx config use proxy /socket.io path

**Comment by mhidea** [comment]
As I said today is the last day
About nginx , that's right. Just follow it. 
How it works?
Ok, all sub domains are redirected to port 443 for ssl.

Then in listen to 443 block , you can set rules for socket.io path because all echo client requests have this path. It's like a trick. 

Of course there are other ways you can config your server, but I think this one is ok and works.

Key is how to use subdomains and set different rules for each one.

I guess you have one domain and 3 different things.

Vue: use domain without subdoamin
Laravel: use api subdoamin
Echo: I recommend using echo subdomain.

Mine worked with this method.

**Comment by inagamov** [comment]
I don't understand where you state echo subdomain. I can only see /socket.io from the main domain

With your nginx config it is possible to access laravel-echo-server by `domain.com/socket.io`, not `echo.domain.com`

I have pretty much similar config, but still can't get how to do the magic. Please help😔

**Comment by inagamov** [comment]
By the way, why is it the last day? You are going on holiday or something?
I will try my best to finish it today!

**Comment by inagamov** [comment]
Wait, I think I start understanding how it works...

**Comment by inagamov** [comment]
Is it the same config you used when you were testing?

**Comment by inagamov** [comment]
So, I do get the point that we proxy /socket.io and with some magic it is being used for subdomain, but which domain?

**Comment by mhidea** [comment]
In this repo , check bootsrtap.js 
You'll  see echo subdomain in echo client. check it [here](https://github.com/mhidea/laravel-echo-nginx/blob/6ec08aa825c7ed687ea57961fb090d45056935cf/js/bootstrap.js#L63)

in server.config , [here](https://github.com/mhidea/laravel-echo-nginx/blob/6ec08aa825c7ed687ea57961fb090d45056935cf/server.conf#L3) , I'm redirecting all subdomains to port 443 
 to force them use ssl.

This is minimum config. As I said earlier this way you can apply different rules to each subdomain.

I'll be busy for next 40 days. Life is hard man, I need to find job.

**Comment by inagamov** [comment]
The solution that worked for me:
1. Apply changes from https://github.com/inagamov/chat_bug_fix (check commits from @mhidea )
2. Change `host: 'https://example.com/socket.io'` to just `host: 'https://example.com'` where you initiate laravel-echo server
